BEGIN TRANSACTION;

PRINT '===== BEFORE DELETE =====';

-- ตรวจข้อมูลก่อนลบ
SELECT 'MT_AUDIT_LOG' AS TABLE_NAME, COUNT(*) AS ROWS FROM MT_AUDIT_LOG;
SELECT 'MT_TXN'        AS TABLE_NAME, COUNT(*) AS ROWS FROM MT_TXN;
SELECT 'MT_STOCK'      AS TABLE_NAME, COUNT(*) AS ROWS FROM MT_STOCK;
SELECT 'MT_PART_ITEM'  AS TABLE_NAME, COUNT(*) AS ROWS FROM MT_PART_ITEM;
SELECT 'MT_LOCATION'   AS TABLE_NAME, COUNT(*) AS ROWS FROM MT_LOCATION;


PRINT '===== DELETE PROCESS =====';

-- ลบตามลำดับ FK (Child -> Parent)
DELETE FROM MT_AUDIT_LOG;
PRINT 'Deleted MT_AUDIT_LOG';

DELETE FROM MT_TXN;
PRINT 'Deleted MT_TXN';

DELETE FROM MT_STOCK;
PRINT 'Deleted MT_STOCK';

-- ถ้ามี MT_PART_SUPPLIER ใช้ด้วย ให้ลบก่อน PART
IF OBJECT_ID('MT_PART_SUPPLIER') IS NOT NULL
BEGIN
    DELETE FROM MT_PART_SUPPLIER;
    PRINT 'Deleted MT_PART_SUPPLIER';
END

DELETE FROM MT_PART_ITEM;
PRINT 'Deleted MT_PART_ITEM';

DELETE FROM MT_LOCATION;
PRINT 'Deleted MT_LOCATION';


PRINT '===== AFTER DELETE =====';

-- ตรวจหลังลบ
SELECT 'MT_AUDIT_LOG' AS TABLE_NAME, COUNT(*) AS ROWS FROM MT_AUDIT_LOG;
SELECT 'MT_TXN'        AS TABLE_NAME, COUNT(*) AS ROWS FROM MT_TXN;
SELECT 'MT_STOCK'      AS TABLE_NAME, COUNT(*) AS ROWS FROM MT_STOCK;
SELECT 'MT_PART_ITEM'  AS TABLE_NAME, COUNT(*) AS ROWS FROM MT_PART_ITEM;
SELECT 'MT_LOCATION'   AS TABLE_NAME, COUNT(*) AS ROWS FROM MT_LOCATION;


-- ✅ Safety step:
-- ตอนแรกให้ใช้ ROLLBACK เพื่อตรวจสอบก่อน
-- ถ้ามั่นใจแล้วค่อยเปลี่ยนเป็น COMMIT

--ROLLBACK;  -- ✅ ใช้ตอน test
COMMIT;       -- ✅ ใช้จริง
